import { Route } from "@angular/router";
import { AboutComponent } from "./templates/shared/about/about.component";
import { BuyerComponent } from "./templates/shared/buyer/buyer.component";
import { CalculatorComponent } from "./templates/shared/calculator/calculator.component";
import { ContactComponent } from "./templates/shared/contact/contact.component";
import { FeaturedListingsComponent } from "./templates/shared/featured-listings/featured-listings.component";
import { MapComponent } from "./templates/shared/map/map.component";
import { PropertyDetailComponent } from "./templates/shared/propertydetail/propertydetail.component";
import { SearchPageComponent } from "./templates/shared/search-page/search-page.component";
import { SellerComponent } from "./templates/shared/seller/seller.component";
import { SellerdetailComponent } from "./templates/shared/sellerdetail/sellerdetail.component";
import { Sellerdetail2Component } from "./templates/shared/sellerdetail2/sellerdetail2.component";
import { Sellerdetail3Component } from "./templates/shared/sellerdetail3/sellerdetail3.component";
import { T1HomeComponent } from "./templates/t1/t1-home/t1-home.component";
import { T10HomeComponent } from "./templates/t10/t10-home/t10-home.component";
import { T11HomeComponent } from "./templates/t11/t11-home/t11-home.component";
import { T12HomeComponent } from "./templates/t12/t12-home/t12-home.component";
import { T13HomeComponent } from "./templates/t13/t13-home/t13-home.component";
import { T14HomeComponent } from "./templates/t14/t14-home/t14-home.component";
import { T15HomeComponent } from "./templates/t15/t15-home/t15-home.component";
import { T16HomeComponent } from "./templates/t16/t16-home/t16-home.component";
import { T17HomeComponent } from "./templates/t17/t17-home/t17-home.component";
import { T18HomeComponent } from "./templates/t18/t18-home/t18-home.component";
import { T19HomeComponent } from "./templates/t19/t19-home/t19-home.component";
import { T2HomeComponent } from "./templates/t2/t2-home/t2-home.component";
import { T3HomeComponent } from "./templates/t3/t3-home/t3-home.component";
import { T4HomeComponent } from "./templates/t4/t4-home/t4-home.component";
import { T5HomeComponent } from "./templates/t5/t5-home/t5-home.component";
import { T6HomeComponent } from "./templates/t6/t6-home/t6-home.component";
import { T7HomeComponent } from "./templates/t7/t7-home/t7-home.component";
import { T8HomeComponent } from "./templates/t8/t8-home/t8-home.component";
import { T9HomeComponent } from "./templates/t9/t9-home/t9-home.component";



export interface TemplateRoute {
	path: string;
	component: any;
}

export interface TemplateRoutes {
	[key: string]: Route[];
}

export const templates: TemplateRoutes = {
	t1: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T1HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t2: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T2HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t3: [
		{ path: "", redirectTo: "home", pathMatch: "full" },
		{ path: "home", component: T3HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t4: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T4HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t5: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T5HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t6: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T6HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t7: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T7HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t8: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T8HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t9: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T9HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t10: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T10HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t11: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T11HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t12: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T12HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t13: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T13HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t14: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T14HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t15: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T15HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t16: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T16HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t17: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T17HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t18: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T18HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
	t19: [
		{ path: "", redirectTo: "/home", pathMatch: "full" },
		{ path: "home", component: T19HomeComponent },
		{ path: "search", component: SearchPageComponent },
		{ path: "featured-listings", component: FeaturedListingsComponent },
		{ path: "property-detail", component: PropertyDetailComponent },
		{ path: "map", component: MapComponent },
		{ path: "buyer", component: BuyerComponent },
		{ path: "contact", component: ContactComponent },
		{ path: "calculator", component: CalculatorComponent },
		{ path: "seller", component: SellerComponent },
		{ path: "sellerdetails", component: SellerdetailComponent },
		{ path: "sellerdetails2", component: Sellerdetail2Component },
		{ path: "sellerdetails3", component: Sellerdetail3Component },
		{ path: "about", component: AboutComponent },
	],
};
